#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 28 10:51:44 GMT+01:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=2
shaderPack=ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6
