#Server Country Flags properties file
#Thu Mar 26 19:15:19 GMT+01:00 2026
borderColor=(65, 65, 65, 255)
displayCooldownFlag=true
displayUnknownFlag=true
flagBorder=true
flagPosition=behindName
forceEnglish=false
mapButton=true
mapButtonRight=true
reloadOnRefresh=false
resolveRedirects=true
serverBrowserIntegration=true
showDistance=true
showDistrict=false
showHomeOnMap=false
showISP=false
useKm=true
